export const aiConfig = {
  dailyCallLimit: Number(process.env.AI_DAILY_CALL_LIMIT || 200),
  chatDailyPerIp: Number(process.env.AI_CHAT_DAILY_PER_IP || 15),
  interviewDailyPerIp: Number(process.env.AI_INTERVIEW_DAILY_PER_IP || 10),
  interviewRecruiterDailyPerIp: Number(process.env.AI_INTERVIEW_RECRUITER_DAILY_PER_IP || 25),
  maxOutputTokens: Number(process.env.AI_MAX_OUTPUT_TOKENS || 256),
  knowledgeMaxChars: Number(process.env.AI_KNOWLEDGE_MAX_CHARS || 800),
  cacheTtlChat: Number(process.env.AI_CACHE_TTL_CHAT || 2592000),
  cacheTtlInterview: Number(process.env.AI_CACHE_TTL_INTERVIEW || 2592000),
  cacheTtlComplexity: Number(process.env.AI_CACHE_TTL_COMPLEXITY || 604800),
  cacheTtlJobFit: Number(process.env.AI_CACHE_TTL_JOB_FIT || 86400),
  cacheTtlDebrief: Number(process.env.AI_CACHE_TTL_DEBRIEF || 604800),
  cacheTtlCodeReview: Number(process.env.AI_CACHE_TTL_CODE_REVIEW || 2592000),
  jobFitDailyPerIp: Number(process.env.AI_JOB_FIT_DAILY_PER_IP || 3),
  debriefDailyPerIp: Number(process.env.AI_DEBRIEF_DAILY_PER_IP || 5),
  codeReviewDailyPerIp: Number(process.env.AI_CODE_REVIEW_DAILY_PER_IP || 10),
  blogExplainDailyPerIp: Number(process.env.AI_BLOG_EXPLAIN_DAILY_PER_IP || 10),
  jobDescriptionMaxChars: Number(process.env.AI_JOB_DESCRIPTION_MAX_CHARS || 2000),
  codeReviewMaxChars: Number(process.env.AI_CODE_REVIEW_MAX_CHARS || 4000),
  debriefMinTurns: Number(process.env.AI_DEBRIEF_MIN_TURNS || 3),
  maxOutputTokensDetailed: Number(process.env.AI_MAX_OUTPUT_TOKENS_DETAILED || 512),
  maxHistoryTurns: Number(process.env.AI_MAX_HISTORY_TURNS || 4),
  knowledgeCacheMs: Number(process.env.AI_KNOWLEDGE_CACHE_MS || 60000),
  model: process.env.AI_GEMINI_MODEL || 'gemini-3.1-flash-lite',
  streamingEnabled: process.env.AI_STREAMING_ENABLED !== 'false',
}
